name: My Workflow
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: 'https://github.com/EpitechPromo2027/B-DOP-200-LYN-2-1-bschocolatine-gatien.rittner.git'
  EXECUTABLES: 'pushswap,lib/my/libmy.a'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Check Coding Style
        run: check.sh $(pwd) $(pwd)
        continue-on-error: true
      - name: Display Annotations
        uses: "msoedov/github-actions-annotate-build@v1"
        with:
          path: '.'
          file_regex: '\.c$|\.h$'
      - name: Fail on Error
        run: 'echo "Coding style errors detected!" && exit 1'
        if: ${{ steps.display_annotations.outputs.errors > 0 }}

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_coding_style
    steps:
      - name: Build
        run: make
      - name: Clean
        run: make clean
      - name: Verify Executables
        run: |
          for exe in $(echo "$EXECUTABLES" | tr ',' ' '); do
            if [ ! -x "$exe" ]; then
              echo "$exe is not executable or does not exist!"
              exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_program_compilation
    steps:
      - name: Run Tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: run_tests
    env:
      GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    steps:
      - name: Push to Mirror
        uses: appleboy/ssh-action@master
        with:
          host: example.com
          username: myuser
          key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git push "$MIRROR_URL" HEAD:main
