name: My Workflow
on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-LYN-2-1-chocolatine-leo.bauduin.git"
  EXECUTABLES: "mysh"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Check Coding Style
        run: |
          check.sh $(pwd) $(pwd)
          if [[ -s coding-style-reports.log ]];
          then
            echo "Coding style errors detected :";
            cat coding-style-reports.log;
            exit 1;
          else
            echo "No coding style detected";
            exit 0
          fi

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    needs: check_coding_style

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make
        timeout-minutes: 2
      - name: Verify Executables
        run: |
          for exe in $(echo "$EXECUTABLES" | tr ',' ' '); do
            if [ ! -x "$exe" ]; then
              echo "$exe is not executable or does not exist!"
              exit 1
            fi
          done
      - name: Clean
        run: make clean

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: make tests_run

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}